name: Mailboxes
version: 0.4-alpha-1
main: dansplugins.mailbox.Mailbox
api-version: 1.13

commands:
  mailboxes:
  m:

permissions:
  mailboxes.help:
    default: true
  mailboxes.list:
    default: true
  mailboxes.config:
    default: op