name: Mailboxes
version: 0.8-alpha-1
main: dansplugins.mailboxes.Mailboxes
api-version: 1.13

commands:
  mailboxes:
  m:

permissions:
  mailboxes.help:
    default: true
  mailboxes.list:
    default: true
  mailboxes.send:
    default: true
  mailboxes.open:
    default: true
  mailboxes.delete:
    default: true
  mailboxes.archive:
    default: true
  mailboxes.config:
    default: op